CREATE TABLE IF NOT EXISTS `PRICES` (
            `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `BRAND_ID` BIGINT NOT NULL,
            `START_DATE` TIMESTAMP NOT NULL,
            `END_DATE` TIMESTAMP NOT NULL,
            `PRICE_LIST` INT NOT NULL,
            `PRODUCT_ID` BIGINT NOT NULL,
            `PRIORITY` INT NOT NULL,
            `PRICE` FLOAT NOT NULL,
            `CURR` VARCHAR(3)
);

CREATE INDEX BRAND_INDEX ON PRICES(BRAND_ID);
CREATE INDEX PRODUCT_INDEX ON PRICES(PRODUCT_ID);
CREATE INDEX DATE_INDEX ON PRICES(START_DATE,END_DATE);